### ISSUE TITLE
Change manifold to manifest?

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick-datasets#2]
Should "manifold" be "manifest", [here](https://github.com/DistrictDataLabs/yellowbrick-datasets/blob/c491fa06abfea8e5db59985a7bb120c154f885fc/ybdata/commands/upload.py#L43), [here](https://github.com/DistrictDataLabs/yellowbrick-datasets/blob/c491fa06abfea8e5db59985a7bb120c154f885fc/ybdata/commands/upload.py#L58), and [here](https://github.com/DistrictDataLabs/yellowbrick-datasets/blob/1b3ce03ee3c6b75db4db5398382114caff9252e7/README.md) (last paragraph)?

**Comment by bbengfort** [comment]
Ooft, yeh I can't stop writing manifold ...
